version: '3'

networks:
  laravel:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - PHP_USER=${PHP_USER:-laravel}
    container_name: myblog_nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - db
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./docker/php/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - NGINX_USER=${NGINX_USER:-laravel}
    container_name: myblog_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  composer:
    image: composer:2
    container_name: myblog_composer
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel

  npm:
    image: node:18.16.0
    container_name: myblog_npm
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - laravel